@startuml
ServiceProvider -> ServiceProvider:getYml()
ServiceProvider -> ServiceManager:loadService(yml)
ServiceManager -> ServiceManager: setParserFactory(parserFactory)
ServiceManager -> ServiceManager:setEntryRegister(entryRegister)
ServiceManager -> ServiceManager: buildServiceInstance()
ServiceManager -> ServiceManager: loadEntry(definition)
ServiceManager -> ParserFactory: getParser(type,Entry.class)
ServiceManager -> EntryRegister: registerEntry(entry)
EntryRegister -> EntryHolder: registerEntry(id,entry)
ServiceManager -> ServiceManager: putEntryMap(id,entry)
ServiceManager -> ServiceManager: loadComponent(definition)
ServiceManager -> ParserFactory: getParser(type,Component.class)
ServiceManager -> ServiceManager: putComponentMap(id,component)
@enduml